version: '3.8'

services:
  exercise-api:
    build: .
    ports:
      - "5200:5000"
    volumes:
      - .:/app
    restart: always
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py